### ISSUE TITLE
Configuring which stats to send

### ISSUE THREAD

**Issue by losnir** [raintank/statsdaemon#17]
Hi,

Me and my team are surveying drop-in replacements for statsd - specifically ones that can handle metrics 2.0 well.

We thought that statsdaemon can be a good candidate, but we are concerned about the massive amounts of irrelevant stats being sent.

For instance, we really have no use for the `pckt_*` metrics, as well for `std` / `median` / `sum` metrics.

Looking at the source code / readme, unfortunately they do not seem to be configurable.

I understand those can be filtered out using carbon-relay black/white list, however this will cause unnecessary network / CPU overhead.

Am I missing anything?

Thanks.

**Comment by Dieterbe** [comment]
Not missing anything. I suppose you could comment them out and recompile

**Comment by losnir** [comment]
Thanks, that's what I thought.

In case I do choose to do that, will you consider this a common enough use-case to warrant a PR?

**Comment by Dieterbe** [comment]
i guess i would be open to that
