### ISSUE TITLE
statsdaemon processing time vs statsd 0.8.0 nodejs

### ISSUE THREAD

**Issue by tehlers320** [raintank/statsdaemon#27]
I may be misinterpreting the processing time metric but it looks like the following setup is outperforming statsdaemon at least in the "processing_time" category. I assumed that maybe the 4 nodejs pids should be added up but even so are much less processing time. Is this something to worry about does 600ms equal latency before a metric gets sent to graphite?

**Setup**
statsd-proxy (c-code re-write)
statsd 0.8.0 x4
m4.xlarge  _Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz_ 
statsdaemon v0.6 (built w/go1.8rc2, git hash 1.0.0-12-g1a031b9) (set to nice -1)
carbon-c-relay is behind statsd doing aggregation (set to nice 19 to not steal cycles from statsdaemon)

![screen shot 2017-01-24 at 1 34 56 pm](https://cloud.githubusercontent.com/assets/16598119/22263390/ef34308e-e239-11e6-8f72-1241bab53e16.png)

![screen shot 2017-01-24 at 1 25 28 pm](https://cloud.githubusercontent.com/assets/16598119/22263012/9b5ca69a-e238-11e6-90fe-37144e19b208.png)

There seems to be no performance difference between the two setups other than CPU usage reduction.

CPU usage does go down substantially when the test begins at 10:30 
![screen shot 2017-01-24 at 1 21 01 pm](https://cloud.githubusercontent.com/assets/16598119/22262875/30d73e84-e238-11e6-81b4-2444994cc73c.png)

UDP packet drops (statsdaemon enabled 10:30)
Even though statsdaemon is showing it is more efficient on cpu there are more drops than statd-proxy which uses SO_REUSEPORT (only kernel 3.9+). 
![screen shot 2017-01-24 at 1 19 44 pm](https://cloud.githubusercontent.com/assets/16598119/22263081/cde81c0c-e238-11e6-8e43-56a978714ae1.png)

**Comment by DanCech** [comment]
What are we comparing here?  I'm assuming some part of these graphs is showing statsd and some is showing statsdaemon but I'm unclear what is what

**Comment by tehlers320** [comment]
statsd 0.8.0 processing time vs the aliasByNode(service_is_statsdaemon.instance_is_$instance.statsd_type_is_*.mtype_is_gauge.type_is_calculation.unit_is_ms, 2)

I guess the question is does this metric imply it takes 600ms before it processes the gauges and sends them or am i misreading that.

**Comment by tehlers320** [comment]
Closing i don't want to leave cruft open. I think this is a non issue more importantly is the droprate vs statsd-proxy and that is covered by another issue.
