### ISSUE TITLE
metrics 2.0 

### ISSUE THREAD

**Issue by Alexul** [raintank/statsdaemon#28]
Adding to ini:
**prefix_m20_rates = "source=statsd.dc=aws."
prefix_m20_counters = "source=statsd.dc=aws."
prefix_m20_timers = "source=statsd.dc=aws."
prefix_m20_gauges = "source=statsd.dc=aws."**
Breaks TOML
Error message:
_Could not read config file: /etc/statsdaemon.ini is not a valid TOML file. See https://github.com/mojombo/toml_

**Comment by Dieterbe** [comment]
I worked with Alex and we figured out this is a dup of #24 and works now.
